apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: csecrets.cache.example.com
spec:
  group: cache.example.com
  names:
    kind: CSecrets
    listKind: CSecretsList
    plural: csecrets
    singular: csecrets
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
